<a href="https://colab.research.google.com/github/yashgeed-AI-DS/Numpy/blob/main/class2file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(arr)
# shape
print(arr.shape)
#ndim -> number of dimension
print(arr.ndim)
# size -> Number of elements
print(arr.size)
#dtype -> data types inside your array
print(arr.dtype)

(3, 3)
2
9
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
arr = np.array([10,20,30,40,50])
#1D array indexing and slicing  = List
print(arr[3])
print(arr[-1])
print(arr[-3])

40
50
30


Now lets see the 2D indexing aswell

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
#indexing
# arr[row,column]
print(arr[1,1])
print(arr[1,2])

5
6


In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0:2,0:2]    #rows from 0,1 and columns from 0,1

array([[1, 2],
       [4, 5]])

In [ ]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
arr[1:3,1]

array([5, 8])

Now we can also do the slicing lets see the **slicing in 1D**

1D slicing was really easy now lets see the **slicing in 2D**

There is one more thing known as **Boolean indexing**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr>5)
print((arr[arr>5]))

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [ ]:
#When we have to convert an 1D array into an
#2D array we use, reshape(row,column)
import numpy as np
arr = np.arange(12)
reshaped = arr.reshape(3,4)
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
oneD = arr.flatten()
oneD

array([1, 2, 3, 4, 5, 6, 7, 8, 9])