<a href="https://colab.research.google.com/github/yashgeed-AI-DS/Numpy/blob/main/class3file_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3,])
#1 Addition
print(a+b)
#Subtraction
print(a-b)
# Multiplication
print(a*b)

[11 22 33]
[ 9 18 27]
[10 40 90]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
a = np.array([10,20,30,40])
print(a*5)

[ 50 100 150 200]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
a = np.array([[10,20,30],
             [40,50,60]])
b = np.array([10,20,30])
print(a+b)

[[20 40 60]
 [50 70 90]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
# Basic Statistical Operations perform
# sum,mean,min,max,standard deviation,,variance
arr = np.array([4,78,21,34,100,56])
print(f"Sum is {arr.sum()}")
print(f"Mean(Average): {arr.mean()}")
print(f"Min : {arr.min()}")
print(f"Max : {arr.max()}")
#Standard Deviation
print(f"Standard Deviation : {arr.std()}")
#Variance
print(f"Variance :{arr.var()}")

Sum is 293
Mean(Average): 48.833333333333336
Min : 4
Max : 100
Standard Deviation : 32.97684372741306
Variance :1087.4722222222224


You can also do the axis based operations row-Wise and Colum-wise

In [ ]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(f"Sum of all  : {data .sum()}")
# axis = 0 -> columns
# axis = 1 -> rows
print(f"Sum of columns : {np.sum(data,axis = 0)}")
print(f"Sum of rows : {np.sum(data,axis = 1)}")

Sum of all  : 45
Sum of columns : [12 15 18]
Sum of rows : [ 6 15 24]
