<a href="https://colab.research.google.com/github/yashgeed-AI-DS/Numpy/blob/main/Numpy_4_Assign_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# NumPy Assignment — Fancy Indexing, Conditional Selection, Sorting & Stacking

## Level: Basic

### Topics Covered
- Fancy Indexing
- Conditional Selection
- np.sort()
- np.argsort()
- Concatenation
- Vertical Stacking
- Horizontal Stacking

### Instructions
- Use NumPy in every question.
- Write your solution in the code cell below each question.
- Print the required output.



# Q1. Fancy Indexing (1D Array)

## Problem Statement
Create the array:

```python
[10, 20, 30, 40, 50, 60]
```

Using fancy indexing, print:
- 10
- 30
- 60

## Sample Output
```python
[10 30 60]
```


In [ ]:
import numpy as np
a = np.array([10,20,30,40,50,60])
a[[0,2,5]]

array([10, 30, 60])


# Q2. Fancy Indexing (1D Array)

## Problem Statement
Create the array:

```python
[5, 15, 25, 35, 45]
```

Using fancy indexing, print:
- 15
- 45

## Sample Output
```python
[15 45]
```


In [ ]:
a = np.array([5,15,25,35,45])
a[[1,4]]

array([15, 45])


# Q3. Fancy Indexing (2D Array)

## Problem Statement
Create the matrix:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Using fancy indexing, print:
- 10
- 50
- 90

## Sample Output
```python
[10 50 90]
```


In [ ]:
a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
a[[0,1,2],[0,1,2]]

array([10, 50, 90])


# Q4. Conditional Selection

## Problem Statement
Create the array:

```python
[5, 12, 18, 25, 30, 7]
```

Print only values greater than 15.

## Sample Output
```python
[18 25 30]
```


In [ ]:
a = np.array([5,12,18,25,30,7])
a[a>15]

array([18, 25, 30])


# Q5. Conditional Selection

## Problem Statement
Create the array:

```python
[2, 4, 7, 10, 13, 16]
```

Print only even numbers.

## Sample Output
```python
[ 2  4 10 16]
```


In [ ]:
a = np.array([2,4,7,10,13,16])
a[a%2==0]

array([ 2,  4, 10, 16])


# Q6. Sorting an Array

## Problem Statement
Create the array:

```python
[25, 10, 40, 5, 30]
```

Sort the array using `np.sort()`.

## Sample Output
```python
[ 5 10 25 30 40]
```


In [ ]:
a = np.array([25,10,40,5,30])
np.sort(a)

array([ 5, 10, 25, 30, 40])


# Q7. Find Sorted Indices

## Problem Statement
Create the array:

```python
[50, 20, 70, 10]
```

Use `np.argsort()` to find the indices of sorted elements.

## Sample Output
```python
[3 1 0 2]
```


In [ ]:
a = np.array([50,20,70,10])
np.argsort(a)

array([3, 1, 0, 2])


# Q8. Concatenate Arrays

## Problem Statement
Create two arrays:

```python
arr1 = [1,2,3]
arr2 = [4,5,6]
```

Concatenate both arrays.

## Sample Output
```python
[1 2 3 4 5 6]
```


In [ ]:
arr1 = [1,2,3]
arr2 = [4,5,6]
np.concatenate([arr1,arr2])

array([1, 2, 3, 4, 5, 6])


# Q9. Vertical Stacking

## Problem Statement
Create two arrays:

```python
[1,2,3]
[4,5,6]
```

Combine them using vertical stacking.

## Sample Output
```python
[[1 2 3]
 [4 5 6]]
```


In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6]])


# Q10. Horizontal Stacking

## Problem Statement
Create two arrays:

```python
[10,20,30]
[40,50,60]
```

Combine them using horizontal stacking.

## Sample Output
```python
[10 20 30 40 50 60]
```


In [ ]:
a = np.array([[10,20,30],
              [40,50,60]])
np.hstack(a)

array([10, 20, 30, 40, 50, 60])